{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"Target":
	{
        "EntitySet" : "CrewListItems",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "QueryOptions":"/SAPAssetManager/Rules/Crew/ZFSMCrewListItemQuery.js"
    },

    "Properties": {
        "RemovalFlag": " ",
        "ZPositionID" : "/SAPAssetManager/Rules/Crew/LineItem/ZCrewListItemZPositionID.js"
    },
    "Headers":
	{
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/Crew/Header/ZFSMCrewId.js"
    },
    "OnSuccess": "/SAPAssetManager/Rules/Crew/LineItem/ZCrewListItemProcessFSMLoop.js"
}