{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"Target":
	{
        "EntitySet" : "CrewListItems",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "QueryOptions":"/SAPAssetManager/Rules/Crew/ZDisableNonFSMCrewListItemQuery.js"
    },

    "Properties": {
        "RemovalFlag": "X",
        "RemovalTimeStamp": "/SAPAssetManager/Rules/Crew/LineItem/CrewListItemRemovalTimeStamp.js"
    },
    "Headers":
	{
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/Crew/Header/ZDisableCrewId.js"
    },
    "OnSuccess": "/SAPAssetManager/Rules/Crew/LineItem/ZCrewListItemProcessDisableLoop.js"
}