{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"Target":
	{
		"EntitySet" : "CrewListItems",
		"Service" : "/SAPAssetManager/Services/AssetManager.service"
	},
	"Properties":
	{
        "CrewId" : "/SAPAssetManager/Rules/Crew/Header/CrewListCrewId.js",
        "CrewItemId" : "/SAPAssetManager/Rules/Crew/LineItem/ZCrewListItemCrewItemId.js",
        "CrewItemType" : "/SAPAssetManager/Globals/Crew/ItemTypeEmployee.global",
        "CrewItemKey" : "/SAPAssetManager/Rules/Crew/LineItem/ZCrewListItemCrewItemKeyFSM.js",
        "ZPositionID" : "/SAPAssetManager/Rules/Crew/LineItem/ZCrewListItemZPositionID.js",
        "RemovalFlag" : " ",
        "CatsHours" : "0"
    },
    "CreateLinks": "/SAPAssetManager/Rules/Crew/LineItem/ZCrewListItemFSMLinks.js",
    "Headers":
	{
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/Crew/Header/ZFSMCrewId.js"
    },
    "OnSuccess": "/SAPAssetManager/Rules/Crew/LineItem/ZCrewListItemProcessFSMLoop.js"
}