{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Devices",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "QueryOptions": "$filter=Device eq EquipmentNum"
    },
    "Properties": {
        "ZMeterIRRSummarizedReadingsText": ""
    },
	"Headers":
	{
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/Meter/CreateUpdate/BatchEquipmentNum.js",
        "Transaction.Ignore": "false"
	},
    "ShowActivityIndicator": false,
    "ActivityIndicatorText" : "  "
}
